
/**************************************************************
 *	
 *	dryfire, 8 bit, 11025Hz,
 *	1 channel, 3076 bytes/channel
 *	Total Size: 1 * 3076 + 4 (header) = 3120 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\muehr\Downloads\milestone3\dryfire.wav
 *	Time-stamp: Sun Apr 21 20:32:31 2019
 *	
 **************************************************************/

#ifndef __DRYFIREH__
#define __DRYFIREH__

#define DRYFIREFREQ 11025
#define DRYFIRELEN 3076

extern const unsigned char dryfire[3076];

#endif /* __DRYFIREH__ */
