
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 1038906 bytes/channel
 *	Total Size: 1 * 1038906 + 4 (header) = 1038950 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\muehr\Downloads\milestone3\GameSong.wav
 *	Time-stamp: Wed Apr 17 00:16:58 2019
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 1038906

extern const unsigned char GameSong[1038906];

#endif /* __GAMESONGH__ */
