
/**************************************************************
 *	
 *	hitSFX, 8 bit, 11025Hz,
 *	1 channel, 9156 bytes/channel
 *	Total Size: 1 * 9156 + 4 (header) = 9200 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\muehr\Downloads\milestone3\hitSFX.wav
 *	Time-stamp: Wed Apr 17 00:40:58 2019
 *	
 **************************************************************/

#ifndef __HITSFXH__
#define __HITSFXH__

#define HITSFXFREQ 11025
#define HITSFXLEN 9156

extern const unsigned char hitSFX[9156];

#endif /* __HITSFXH__ */
