
/**************************************************************
 *	
 *	InstructionsSong, 8 bit, 11025Hz,
 *	1 channel, 2335780 bytes/channel
 *	Total Size: 1 * 2335780 + 4 (header) = 2335824 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\muehr\Downloads\milestone3\InstructionsSong.wav
 *	Time-stamp: Wed Apr 17 16:23:44 2019
 *	
 **************************************************************/

#ifndef __INSTRUCTIONSSONGH__
#define __INSTRUCTIONSSONGH__

#define INSTRUCTIONSSONGFREQ 11025
#define INSTRUCTIONSSONGLEN 2335780

extern const unsigned char InstructionsSong[2335780];

#endif /* __INSTRUCTIONSSONGH__ */
