
/**************************************************************
 *	
 *	LoseSong, 8 bit, 11025Hz,
 *	1 channel, 2116997 bytes/channel
 *	Total Size: 1 * 2116997 + 4 (header) = 2117041 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\muehr\Downloads\milestone3\LoseSong.wav
 *	Time-stamp: Thu Apr 18 21:35:57 2019
 *	
 **************************************************************/

#ifndef __LOSESONGH__
#define __LOSESONGH__

#define LOSESONGFREQ 11025
#define LOSESONGLEN 2116997

extern const unsigned char LoseSong[2116997];

#endif /* __LOSESONGH__ */
