
/**************************************************************
 *	
 *	MenuSong, 8 bit, 11025Hz,
 *	1 channel, 724937 bytes/channel
 *	Total Size: 1 * 724937 + 4 (header) = 724981 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\muehr\Downloads\milestone3\MenuSong.wav
 *	Time-stamp: Wed Apr 17 00:17:12 2019
 *	
 **************************************************************/

#ifndef __MENUSONGH__
#define __MENUSONGH__

#define MENUSONGFREQ 11025
#define MENUSONGLEN 724937

extern const unsigned char MenuSong[724937];

#endif /* __MENUSONGH__ */
