
/**************************************************************
 *	
 *	reload2, 8 bit, 11025Hz,
 *	1 channel, 3444 bytes/channel
 *	Total Size: 1 * 3444 + 4 (header) = 3488 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\muehr\Downloads\milestone3\reload2.wav
 *	Time-stamp: Sun Apr 21 20:32:17 2019
 *	
 **************************************************************/

#ifndef __RELOAD2H__
#define __RELOAD2H__

#define RELOAD2FREQ 11025
#define RELOAD2LEN 3444

extern const unsigned char reload2[3444];

#endif /* __RELOAD2H__ */
