
/**************************************************************
 *	
 *	reload1, 8 bit, 11025Hz,
 *	1 channel, 2740 bytes/channel
 *	Total Size: 1 * 2740 + 4 (header) = 2784 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\muehr\Downloads\milestone3\reload1.wav
 *	Time-stamp: Sun Apr 21 20:32:12 2019
 *	
 **************************************************************/

#ifndef __RELOAD1H__
#define __RELOAD1H__

#define RELOAD1FREQ 11025
#define RELOAD1LEN 2740

extern const unsigned char reload1[2740];

#endif /* __RELOAD1H__ */
