
/**************************************************************
 *	
 *	ump45, 8 bit, 11025Hz,
 *	1 channel, 27200 bytes/channel
 *	Total Size: 1 * 27200 + 4 (header) = 27244 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\muehr\Downloads\milestone3\ump45.wav
 *	Time-stamp: Sun Apr 21 20:32:08 2019
 *	
 **************************************************************/

#ifndef __UMP45H__
#define __UMP45H__

#define UMP45FREQ 11025
#define UMP45LEN 27200

extern const unsigned char ump45[27200];

#endif /* __UMP45H__ */
