
/**************************************************************
 *	
 *	StartSFX, 8 bit, 11025Hz,
 *	1 channel, 13009 bytes/channel
 *	Total Size: 1 * 13009 + 4 (header) = 13053 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\muehr\Downloads\milestone3\StartSFX.wav
 *	Time-stamp: Wed Apr 17 00:40:43 2019
 *	
 **************************************************************/

#ifndef __STARTSFXH__
#define __STARTSFXH__

#define STARTSFXFREQ 11025
#define STARTSFXLEN 13009

extern const unsigned char StartSFX[13009];

#endif /* __STARTSFXH__ */
